### ISSUE TITLE
下载之后没反应

### ISSUE THREAD

**Issue by TCOTC** [sublimeclemency/siyuan-theme-dark-tranquility#1]
下载完了外观模式自动变为「暗黑」，但只是模式变了，外观感觉还是思源原生的。

「已下载」中没有内容：
![image](https://github.com/sublimeclemency/siyuan-theme-dark-tranquility/assets/78434827/652328fb-cab7-4f73-8c4c-3ead60dc956c)

再点进去还显示要下载：
![image](https://github.com/sublimeclemency/siyuan-theme-dark-tranquility/assets/78434827/56809b39-da51-4cc2-b4d0-250ec9e2a39f)

**Comment by sublimeclemency** [comment]
this will be fixed; sorry everyone
basically siyuan marketplace looks in the theme repo for "package.zip" and uses that.
i zipped the package incorrectly.

**Comment by frostime** [comment]
Relevant to #2

**Comment by sublimeclemency** [comment]
resolved by updating theme.json :)
