### ISSUE TITLE
打包错误

### ISSUE THREAD

**Issue by frostime** [sublimeclemency/siyuan-theme-dark-tranquility#2]
![image](https://github.com/sublimeclemency/siyuan-theme-dark-tranquility/assets/27268127/3f1bb625-b4fd-4f71-aaa4-b8c1c6bbf7fd)

![image](https://github.com/sublimeclemency/siyuan-theme-dark-tranquility/assets/27268127/f8b5e014-98dd-4a6a-918c-db3ca93320b8)

多了一层 package

**Comment by sublimeclemency** [comment]
my bad
this is fixed in the latest release but this doesn't seem to update for the marketplace

**Comment by sublimeclemency** [comment]
resolved by updating theme.json :)
