### ISSUE TITLE
无法更新

### ISSUE THREAD

**Issue by itachaaa** [sublimeclemency/siyuan-theme-dark-tranquility#3]
大佬，这个主题真的很喜欢，但是就是更新不了（当前是1.1.4）, 不晓得是不是还是打包的问题。更新之后，还是提示要更新。
![image](https://github.com/sublimeclemency/siyuan-theme-dark-tranquility/assets/31896600/22fb1b23-e498-4e67-8fd6-19aa79ec15e6)

**Comment by sublimeclemency** [comment]
thanks! 1.1.4 is actually the latest release
siyuan often has some packaging issues - you can delete themes in the `conf/appearance/themes` directory to help refresh
